id: A6FECE9BB
title: 'Divine Music: Words of Encouragement for the Authentic Path'
type: translation
pechas:
- ID712D944
- IF809A550
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:10.540365
  last_modified_at: 2023-01-04 12:55:10.540387
  collections:
  - Khenpo Shenpen Nangwa Series
  - Works of Tibetan Masters
alignment_to_base:
  ID712D944/4C4C: 9C46
  IF809A550/8AB2: 9C46
